### ISSUE TITLE
Parameter 'url' must be a string, not undefined

### ISSUE THREAD

**Issue by nheidloff** [mattgj/alexa-skills#7]
Matt, your project looks promising since I'd like to develop and deploy an Alexa skill without using Lambda.

I ran into an issue though when I invoke a POST. Any idea what's going on? I use / as route.

Thanks

2016-07-27T11:48:43.65+0200 [App/0]      ERR TypeError: Parameter 'url' must be a string, not undefined
2016-07-27T11:48:43.65+0200 [App/0]      ERR     at Url.parse (url.js:90:11)
2016-07-27T11:48:43.65+0200 [App/0]      ERR     at Object.urlParse [as parse](url.js:84:5)
2016-07-27T11:48:43.65+0200 [App/0]      ERR     at normalizeUrl (/home/vcap/app/node_modules/alexa-skills/node_modules/normalizeurl/lib/normalizeUrl.js:117:42)
2016-07-27T11:48:43.65+0200 [App/0]      ERR     at module.exports (/home/vcap/app/node_modules/alexa-skills/request-validator.js:8:15)
2016-07-27T11:48:43.65+0200 [App/0]      ERR     at Layer.handle [as handle_request](/home/vcap/app/node_modules/express/lib/router/layer.js:95:5)
2016-07-27T11:48:43.65+0200 [App/0]      ERR     at next (/home/vcap/app/node_modules/express/lib/router/route.js:131:13)
2016-07-27T11:48:43.65+0200 [App/0]      ERR     at jsonParser (/home/vcap/app/node_modules/alexa-skills/node_modules/body-parser/lib/types/json.js:112:7)
2016-07-27T11:48:43.65+0200 [App/0]      ERR     at Layer.handle [as handle_request](/home/vcap/app/node_modules/express/lib/router/layer.js:95:5)
2016-07-27T11:48:43.65+0200 [App/0]      ERR     at next (/home/vcap/app/node_modules/express/lib/router/route.js:131:13)
2016-07-27T11:48:43.65+0200 [App/0]      ERR     at Route.dispatch (/home/vcap/app/node_modules/express/lib/router/route.js:112:3)

**Comment by mattgj** [comment]
From your log, it seems to be crashing because the SignatureCertChainUrl header is missing from the POST. This header is used in the request validation process. You can work around this issue by setting that header to any value, but your route will not trigger if the validation is not successful.
